### PR TITLE
Added project files for .NET Core 1.0.

### PR DESCRIPTION
**Pull request by sharpe5**
Added project files for .NET Core 1.0. 

Everything works nicely under both .NET 4.5 and .NET Core 1.0.

Feedback welcome.

### CODE REVIEW

**Comment by sharpe5** [comment]
Worked nicely for .NET Core 1.0, but the .NET 4.5 solution stopped compiling as it was picking up the  project.json files. Will fix tomorrow.

**Comment by drewnoakes** [comment]
Consider using only `project.json` and a single solution file. I've done this with a few projects now and it works well.

Some examples for reference:

https://github.com/drewnoakes/metadata-extractor-dotnet
https://github.com/drewnoakes/dasher
https://github.com/drewnoakes/xmp-core-dotnet

**Comment by drewnoakes** [comment]
We will also have to reconfigure AppVeyor. I'm happy to help with that.

**Comment by sharpe5** [comment]
Ok, thanks for the feedback (.NET Core has a bit of a learning curve). I
will do this tonight.

**Comment by sharpe5** [comment]
I've done as you suggested, and everything is now in a single project file.

Created the pull request.

As part of this, I noticed that Dasher is not compatible with .NET Core
1.0, I'll raise an issue for that.

**Pull request closed without merging**
